vim.pack.add({ "https://github.com/gbprod/substitute.nvim" })

require("substitute").setup({
  on_substitute = function()
    require("yanky.integration").substitute()
  end,
})

vim.keymap.set("n", "s", function()
  require("substitute").operator()
end, { desc = "Substitute Operator" })
vim.keymap.set("n", "ss", function()
  require("substitute").line()
end, { desc = "Substitute Line" })
vim.keymap.set("n", "S", function()
  require("substitute").eol()
end, { desc = "Substitute EOL" })
vim.keymap.set("x", "s", function()
  require("substitute").visual()
end, { desc = "Substitute Selection" })
vim.keymap.set("n", "sx", function()
  require("substitute.exchange").operator()
end, { desc = "Exchange Operator" })
vim.keymap.set("n", "sxx", function()
  require("substitute.exchange").line()
end, { desc = "Exchange Line" })
vim.keymap.set("x", "sx", function()
  require("substitute.exchange").visual()
end, { desc = "Exchange" })
