directory: ~/music
library: ~/.config/beets/musiclibrary.db

format_album: $year-$albumartist-$album ($genre)  https://musicbrainz.org/release-group/$mb_releasegroupid
original_date: yes
sort_album: albumartist+ year+ album+

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>"\?\*\|]': _
    ':': '-'
    '\.$': _
    '\s+$': ''
    '^\s+': ''

import:
    write: yes
    move: yes
    incremental: yes
    log: ~/.config/beets/import.log

plugins:
    - fetchart
    - embedart
 #    - bandcamp
    - ftintitle
    - edit
    - lastgenre
    - scrub
    - info
    - replaygain
    - mbsync
    - missing
#    - beatport


paths:
    default: $albumartist/$year-$album/$track-$artist-$title
    comp: Various Artists/$year-$album/$track-$artist-$title
    singleton: $albumartist/$year-$title/01-$artist-$title

#Plugins Config

fetchart:
    auto: yes
    minwidth: 350
    enforce_ratio: yes

embedart:
    ifempty: yes
    remove_art_file: yes

ftintitle:
    auto: yes
    drop: yes

scrub:
    auto: yes

lastgenre:
    canonical: ~/dotfiles/.config/beets/genres-tree.yaml
    whitelist: ~/dotfiles/.config/beets/genre_whitelist

edit:
    albumfields: album albumartist year genre
    itemfields: track title artist album

bandcamp:
    art: true

replaygain:
    backend: gstreamer

missing:
    format: $year-$albumartist-$album https://musicbrainz.org/release-group/$mb_releasegroupid $missing
