#!/bin/bash

case "$BLOCK_BUTTON" in
    1) pamixer -i 5 ;;
    2) pamixer -t ;;
    3) pamixer -d 5 ;;
    4) pamixer -i 5 ;;
    5) pamixer -d 5 ;;
esac

statusLine=$(pamixer --get-volume-human)

if [[ "${statusLine}" != "muted" ]]; then
  echo "墳 ${statusLine}"
else
  echo " MUTE"
fi
