#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  bluetooth on >/dev/null
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  bluetooth toggle >/dev/null
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  bluetooth off > /dev/null
fi

STATUS=$(bluetooth | grep -wo 'on')

if [[ "${STATUS}" = "on" ]]; then
  echo "on"
else
    echo "off"
fi
