#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  xbacklight -inc 5
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  xbacklight -dec 5
fi

curBrightness=$(xbacklight -get)

percent=${curBrightness%.*}

if [[ "${percent}" -le 0 ]]; then
  exit
fi

echo "${percent}%"
echo ""
